CREATE TABLE regions (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    code VARCHAR(16) NOT NULL UNIQUE,
    name VARCHAR(200) NOT NULL,
    type VARCHAR(32) NOT NULL
);

INSERT INTO regions (code, name, type) VALUES
    ('RU-AD', 'Республика Адыгея', 'republic'),
    ('RU-AL', 'Республика Алтай', 'republic'),
    ('RU-BA', 'Республика Башкортостан', 'republic'),
    ('RU-BU', 'Республика Бурятия', 'republic'),
    ('RU-DA', 'Республика Дагестан', 'republic'),
    ('RU-IN', 'Республика Ингушетия', 'republic'),
    ('RU-KB', 'Кабардино-Балкарская Республика', 'republic'),
    ('RU-KL', 'Республика Калмыкия', 'republic'),
    ('RU-KC', 'Карачаево-Черкесская Республика', 'republic'),
    ('RU-KR', 'Республика Карелия', 'republic'),
    ('RU-KO', 'Республика Коми', 'republic'),
    ('RU-CR', 'Республика Крым', 'republic'),
    ('RU-ME', 'Республика Марий Эл', 'republic'),
    ('RU-MO', 'Республика Мордовия', 'republic'),
    ('RU-SA', 'Республика Саха (Якутия)', 'republic'),
    ('RU-SE', 'Республика Северная Осетия — Алания', 'republic'),
    ('RU-TA', 'Республика Татарстан', 'republic'),
    ('RU-TY', 'Республика Тыва', 'republic'),
    ('RU-UD', 'Удмуртская Республика', 'republic'),
    ('RU-KK', 'Республика Хакасия', 'republic'),
    ('RU-CE', 'Чеченская Республика', 'republic'),
    ('RU-CU', 'Чувашская Республика', 'republic'),
    ('RU-ALT', 'Алтайский край', 'krai'),
    ('RU-ZAB', 'Забайкальский край', 'krai'),
    ('RU-KAM', 'Камчатский край', 'krai'),
    ('RU-KDA', 'Краснодарский край', 'krai'),
    ('RU-KYA', 'Красноярский край', 'krai'),
    ('RU-PER', 'Пермский край', 'krai'),
    ('RU-PRI', 'Приморский край', 'krai'),
    ('RU-STA', 'Ставропольский край', 'krai'),
    ('RU-KHA', 'Хабаровский край', 'krai'),
    ('RU-AMU', 'Амурская область', 'oblast'),
    ('RU-ARK', 'Архангельская область', 'oblast'),
    ('RU-AST', 'Астраханская область', 'oblast'),
    ('RU-BEL', 'Белгородская область', 'oblast'),
    ('RU-BRY', 'Брянская область', 'oblast'),
    ('RU-VLA', 'Владимирская область', 'oblast'),
    ('RU-VGG', 'Волгоградская область', 'oblast'),
    ('RU-VLG', 'Вологодская область', 'oblast'),
    ('RU-VOR', 'Воронежская область', 'oblast'),
    ('RU-IVA', 'Ивановская область', 'oblast'),
    ('RU-IRK', 'Иркутская область', 'oblast'),
    ('RU-KGD', 'Калининградская область', 'oblast'),
    ('RU-KLU', 'Калужская область', 'oblast'),
    ('RU-KEM', 'Кемеровская область', 'oblast'),
    ('RU-KIR', 'Кировская область', 'oblast'),
    ('RU-KOS', 'Костромская область', 'oblast'),
    ('RU-KGN', 'Курганская область', 'oblast'),
    ('RU-KRS', 'Курская область', 'oblast'),
    ('RU-LEN', 'Ленинградская область', 'oblast'),
    ('RU-LIP', 'Липецкая область', 'oblast'),
    ('RU-MAG', 'Магаданская область', 'oblast'),
    ('RU-MOS', 'Московская область', 'oblast'),
    ('RU-MUR', 'Мурманская область', 'oblast'),
    ('RU-NIZ', 'Нижегородская область', 'oblast'),
    ('RU-NGR', 'Новгородская область', 'oblast'),
    ('RU-NVS', 'Новосибирская область', 'oblast'),
    ('RU-OMS', 'Омская область', 'oblast'),
    ('RU-ORE', 'Оренбургская область', 'oblast'),
    ('RU-ORL', 'Орловская область', 'oblast'),
    ('RU-PNZ', 'Пензенская область', 'oblast'),
    ('RU-PSK', 'Псковская область', 'oblast'),
    ('RU-ROS', 'Ростовская область', 'oblast'),
    ('RU-RYA', 'Рязанская область', 'oblast'),
    ('RU-SAM', 'Самарская область', 'oblast'),
    ('RU-SAR', 'Саратовская область', 'oblast'),
    ('RU-SAK', 'Сахалинская область', 'oblast'),
    ('RU-SVE', 'Свердловская область', 'oblast'),
    ('RU-SMO', 'Смоленская область', 'oblast'),
    ('RU-TAM', 'Тамбовская область', 'oblast'),
    ('RU-TVE', 'Тверская область', 'oblast'),
    ('RU-TOM', 'Томская область', 'oblast'),
    ('RU-TUL', 'Тульская область', 'oblast'),
    ('RU-TYU', 'Тюменская область', 'oblast'),
    ('RU-ULY', 'Ульяновская область', 'oblast'),
    ('RU-CHE', 'Челябинская область', 'oblast'),
    ('RU-YAR', 'Ярославская область', 'oblast'),
    ('RU-MOW', 'Москва', 'federal_city'),
    ('RU-SPE', 'Санкт-Петербург', 'federal_city'),
    ('RU-SEV', 'Севастополь', 'federal_city'),
    ('RU-YEV', 'Еврейская автономная область', 'autonomous_oblast'),
    ('RU-NEN', 'Ненецкий автономный округ', 'autonomous_okrug'),
    ('RU-KHM', 'Ханты-Мансийский автономный округ — Югра', 'autonomous_okrug'),
    ('RU-CHU', 'Чукотский автономный округ', 'autonomous_okrug'),
    ('RU-YAN', 'Ямало-Ненецкий автономный округ', 'autonomous_okrug');
